services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ott_database

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

  metabase:
    image: metabase/metabase:latest
    container_name: metabase

    ports:
      - "3000:3000"

    depends_on:
      - postgres

    volumes:
      - metabase_data:/metabase-data

    environment:
      MB_DB_FILE: /metabase-data/metabase.db

    restart: unless-stopped

volumes:
  postgres_data:
  metabase_data: